<!-- Start Email Section -->
	<section class="foot-email">
		<h6 id="foot-h6">foot email</h6>
		<p>
		<a href="mailto:101028715@student.swin.edu.au" >Email us your queries</a>
		<i class="material-icons">email</i>
		</p>
	</section>
<!-- End Email Section -->
<!-- Start Footer -->
	<footer class="foot">
		<p>2017 &#169; Copyright Blueknights Technologies All Rights Reserved.</p>
	</footer>
<!-- End Footer -->
</body>
<!-- End Body -->
</html>
