<!DOCTYPE html>
<html lang="en">
<!-- Start Head -->
<head>
	<title>BLUEKNIGHTS TECHNOLOGIES</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="Systems Software Engineer" />
	<meta name="keywords" content="Software, Engineer, Job Description" />
	<meta name="author" content="Mustaque Halder" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="styles/style.css"  />
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
</head>
<!-- End Head -->
<!-- Start Body -->
<body>
