<!-- Start Header -->
		<h1>BLUEKNIGHTS TECHNOLOGIES</h1>
	<header>
<!-- Start Nav -->
		<nav>
			<a href="#" id="menu-icon"></a>
				<ul>
				<li><a href="index.php" class="<?php if($currentPage == 'index'){ echo 'active'; } ?>">HOME</a></li>
				<li><a href="jobs.php" class="<?php if($currentPage == 'jobs'){ echo 'active'; } ?>">POSITION DESCRIPTIONS</a></li>
				<li><a href="apply.php" class="<?php if($currentPage == 'apply'){ echo 'active'; } ?>">JOB APPLICATION</a></li>
				<li><a href="about.php" class="<?php if($currentPage == 'about'){ echo 'active'; } ?>">ABOUT</a></li>
        <li><a href="manage.php" class="<?php if($currentPage == 'manage'){ echo 'active'; } ?>">MANAGE</a></li>
				<li><a href="enhancements.php" class="<?php if($currentPage == 'enhancements'){ echo 'active'; } ?>">ENHANCEMENTS</a></li>
				<li><a href="enhancements2.php" class="<?php if($currentPage == 'enhancements2'){ echo 'active'; } ?>">ENHANCEMENTS 2</a></li>
        <li><a href="phpenhancements.php" class="<?php if($currentPage == 'phpenhancements'){ echo 'active'; } ?>">PHPENHANCEMENTS</a></li>
				</ul>
		</nav>
<!-- End Nav -->
	</header>
<!-- End Header -->
<!-- Start Banner-->
	<section class="banner">
		<h6 id="banner-h6">Banner Image</h6>
		<img src="images/banner8.png" alt="Banner-image" />
	</section>
<!-- End Banner -->
